services:
  - type: web
    name: markdownmaven
    env: node
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      # DATABASE_URL should be set manually in Render dashboard

